spring.application.name=auth-service

server.port=8089

# Database configuration (Isolated PostgreSQL Schema)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql:5432/patient_db?currentSchema=auth_schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_pass_123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Explicitly set the default schema for Hibernate to find tables in auth_schema
spring.jpa.properties.hibernate.default_schema=auth_schema

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

app.secret=${APP_SECRET:mySecretKeyForJwtTokenWhichMustBeAtLeast256BitsLong}
app.expiration=3600000

metrics.recording.level=OFF

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=auth-service

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
