spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql:5432/patient_db?currentSchema=patient_schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:patient_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:patient_pass_123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Explicitly set the default schema for Hibernate to find tables in patient_schema
spring.jpa.properties.hibernate.default_schema=patient_schema

# Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

metrics.recording.level=OFF
