app.secret=${APP_SECRET}
spring.security.user.name=
spring.security.user.password=
spring.main.allow-bean-definition-overriding=true

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=api-gateway