app.secret=${APP_SECRET}
spring.security.user.name=
spring.security.user.password=

# Tracing & Observation
management.tracing.sampling.probability=1.0
spring.kafka.producer.observation-enabled=true
spring.kafka.listener.observation-enabled=true
spring.main.allow-bean-definition-overriding=true

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=api-gateway