version: "3.8"

services:
  analytics-service:
    build: .
    image: analytics-service:latest
    container_name: analytics-service
    networks:
      - patient-management_patient-net
    ports:
        - "8082:8082"
        - "9002:9002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
    patient-management_patient-net:
      external: true