# Auth-Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-auth:5432/auth_database
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-auth-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth-secret
              key: POSTGRES_PASSWORD

---
# Auth-Service Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: patient-management
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP