version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - patient-net

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./src:/app/src
    networks:
      - patient-net

volumes:
  postgres-data:

networks:
  patient-net:
    driver: bridge
