version: "3.8"

services:
  billing-service:
    build: .
    image: billing-service:latest
    container_name: billing-service
    networks:
      - patient-network
    ports:
      - "8081:8081"
      - "9001:9001"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


networks:
  patient-network:
    external: true
