name: CI - API Gateway

on:
  push:
    branches: [ "master" ]
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: api-gateway
      context: ./api-gateway
      dockerfile: ./api-gateway/Dockerfile
