name: CI - Docker Build & Push for appointment-service

on:
  push:
    branches:
      - master
    paths:
      - 'appointment-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for appointment-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest ./appointment-service

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest
