name: CI - Appointment Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'appointment-service/**'
      - '.github/workflows/appointment-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: appointment-service
      context: ./appointment-service
      dockerfile: ./appointment-service/Dockerfile
