name: CI - Billing Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'billing-service/**'
      - '.github/workflows/billing-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: billing-service
      context: ./billing-service
      dockerfile: ./billing-service/Dockerfile
