name: CI - Doctor Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'doctor-service/**'
      - '.github/workflows/doctor-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: doctor-service
      context: ./doctor-service
      dockerfile: ./doctor-service/Dockerfile
