name: CI - Inventory Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'inventory-service/**'
      - '.github/workflows/inventory-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: inventory-service
      context: ./inventory-service
      dockerfile: ./inventory-service/Dockerfile
