name: CI - Lab Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'lab-service/**'
      - '.github/workflows/lab-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: lab-service
      context: ./lab-service
      dockerfile: ./lab-service/Dockerfile
