name: CI - Notification Service

on:
  push:
    branches: [ "master" ]
    paths:
      - 'notification-service/**'
      - '.github/workflows/notification-service.yml'
      - 'patient-management-bom/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      service-name: notification-service
      context: ./notification-service
      dockerfile: ./notification-service/Dockerfile
